[tools]
java = "21"
maven = "3.9.9"

[env]
_.path = ["{{ vars.mise_bin_dir }}"]

[vars]
mise_bin_dir = "{{ config_root }}/.mise_bin"

[hooks]
enter = "mise run build"

[tasks.build]
hide = true
silent = true
run = """
    # mise install
    mise install &> /dev/null

    # Install the packages
    rm -rf {{ vars.mise_bin_dir }}
    mkdir -p {{ vars.mise_bin_dir }}
    echo 'mvn com.github.johnpoth:jshell-maven-plugin:1.0:run  $@' > {{ vars.mise_bin_dir }}/jshell
    chmod +x {{ vars.mise_bin_dir }}/jshell
"""

[settings]
experimental = true
