logging:
    level:
        '*':                                     info
        org.springframework.boot.context.config: debug
server:
    compression:
        enabled:           true
        mime-types:
            - text/html
            - text/xml
            - text/plain
            - application/json
        min-response-size: 1024
    error.include-stacktrace: never
    port:                     8081
spring:
    application.name:         consent
    cache.caffeine.spec:      maximumSize=500,expireAfterAccess=600s
    config.import:            file:./secrets.yml
    datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-timeout: 30000
            idle-timeout:       300000
            max-lifetime:       1800000
            maximum-pool-size:  20
            minimum-idle:       5
        password:          ${CONSENT_DB_PASSWORD}
        url:               jdbc:postgresql://localhost:5432/consent
        username:          ${CONSENT_DB_USERNAME:shobhit.aggarwal}
    devtools:
        add-properties:  true
        restart.enabled: true
    jpa:
        hibernate.ddl-auto: validate
        open-in-view:       false
        properties.hibernate:
            connection:
                autocommit: true
                isolation:  TRANSACTION_REPEATABLE_READ
                pool_size:  20
            format_sql:                       true
            jdbc.lob.non_contextual_creation: true
            transaction.jta.platform:         org.hibernate.service.jta.platform.internal.JBossAppServerJtaPlatform
        show-sql:           true
    mail:
        host:     smtp.gmail.com
        password: ${MAIL_PASSWORD}
        port:     587
        properties.mail.smtp:
            auth:     true
            starttls: true
        username: ${MAIL_USERNAME}
    main.lazy-initialization: true
    quartz:
        auto-startup:           false
        jdbc.initialize-schema: never
        job-store-type:         jdbc
        properties.org.quartz.threadPool:
            class:            org.quartz.simpl.SimpleThreadPool
            threadCount:      5
            threadNamePrefix: quartz-worker-
            threadPriority:   5
    security.user:
        name:     consent
        password: ${CONSENT_SECURITY_PASSWORD:consent}
    threads.virtual.enabled:  true
